server:
  port: 5001
  tomcat:
      max-connections: 1200
      max-threads: 1000

region:
  datasource:
    url: 192.168.1.34
    username: root
    password: qwer223
    databaseName: argo-region-man
    urlname: jdbc:mysql://192.168.1.34:3306/argo-region-man?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&&useSSL=false&&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 20
    minIdle: 20
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 1200
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mq:
    maxThreads: 100
    maxCount: 10

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.34
    port: 5672
    username: ARGO
    password: xq3askJWmegaewdkf;la3qdawef

logging:
  slf4j:
    enabled: true
  rabbitmq:
    enabled: true
    exchangeName: log
    declareExchange: true
  project:
    application: argo-region-man
